# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-deepvariant-1.1dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # - conda-forge::python=3.7.3
  # - conda-forge::markdown=3.1.1
  # - conda-forge::pymdown-extensions=6.0
  # - conda-forge::pygments=2.5.2
  # TODO nf-core: Update the dependencies below
  - python=2.7.15
  - pip=10.0.1
  - deepvariant=0.7.0
  - picard=2.18.7
  - samtools=1.9
  - htslib=1.9
  - lbzip2=2.5
  - bzip2=1.0.6
